src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @UniqueEntity("url")
 */
class Article
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $publishedAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $preview;

    /**
     * @ORM\Column(type="text")
     */
    private $content;

    /**
     * @ORM\ManyToMany(targetEntity=Theme::class, inversedBy="articles")
     */
    private $themes;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $directory;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $coverWidth;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $coverHeight;

    public function __construct()
    {
        $this->themes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPublishedAt(): ?DateTimeInterface
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getPreview(): ?string
    {
        return $this->preview;
    }

    public function setPreview(?string $preview): self
    {
        $this->preview = $preview;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    /**
     * @return Collection|Theme[]
     */
    public function getThemes(): Collection
    {
        return $this->themes;
    }

    public function addTheme(Theme $theme): self
    {
        if (!$this->themes->contains($theme)) {
            $this->themes[] = $theme;
        }

        return $this;
    }

    public function removeTheme(Theme $theme): self
    {
        $this->themes->removeElement($theme);

        return $this;
    }

    public function getDirectory(): ?string
    {
        return $this->directory;
    }

    public function setDirectory(string $directory): self
    {
        $this->directory = $directory;

        return $this;
    }

    public function getCoverWidth(): ?int
    {
        return $this->coverWidth;
    }

    public function setCoverWidth(?int $coverWidth): self
    {
        $this->coverWidth = $coverWidth;

        return $this;
    }

    public function getCoverHeight(): ?int
    {
        return $this->coverHeight;
    }

    public function setCoverHeight(?int $coverHeight): self
    {
        $this->coverHeight = $coverHeight;

        return $this;
    }
}

src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use DateTime;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\String\Slugger\AsciiSlugger;
use Symfony\Component\Validator\Constraints as Assert;
use function Symfony\Component\String\s;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment implements RequestInfoInterface
{
    use RequestInfoTrait;

    const STATUS_NEW = 'new';
    const STATUS_NOTIFIED = 'notified';
    const STATUS_SPAM = 'spam';
    const STATUS_MANUAL = 'manual';
    const STATUS_VERIFIED = 'verified';

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $url;

    /**
     * @ORM\Column(type="text")
     * @Assert\NotBlank()
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     */
    private $author;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank()
     * @Assert\Email()
     */
    private $email;

    /**
     * @var DateTime
     *
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $status;

    /**
     * @ORM\ManyToOne(targetEntity=Comment::class, inversedBy="children")
     */
    private $parent;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="parent")
     */
    private $children;

    public function __construct()
    {
        $this->children = new ArrayCollection();
    }

    /**
     * Get the possible statuses of this comment.
     *
     * @return string[]
     */
    public function getPossibleStatuses(): array
    {
        $statuses = [$this->status];

        switch ($this->status) {
            case self::STATUS_NEW:
            case self::STATUS_VERIFIED:
            case self::STATUS_NOTIFIED:
                $statuses = array_merge($statuses, [self::STATUS_SPAM]);
                break;

            case self::STATUS_MANUAL:
                $statuses = array_merge($statuses, [self::STATUS_VERIFIED, self::STATUS_SPAM]);
                break;

            case self::STATUS_SPAM:
                $statuses = array_merge($statuses, [self::STATUS_VERIFIED, self::STATUS_NOTIFIED]);
                break;

            default:
                break;
        }

        return array_unique($statuses);
    }

    public function getAnchor(): string
    {
        $slugger = new AsciiSlugger();

        return 'comment_' . $slugger->slug($this->author) . 'on' . $this->createdAt->getTimestamp();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUrl(): ?string
    {
        return $this->url;
    }

    public function setUrl(string $url): self
    {
        $this->url = $url;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getAuthor(): ?string
    {
        return $this->author;
    }

    public function setAuthor(string $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getCreatedAt(): ?DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getParent(): ?self
    {
        return $this->parent;
    }

    public function setParent(?self $parent): self
    {
        $this->parent = $parent;

        return $this;
    }

    /**
     * @return Collection|self[]
     */
    public function getChildren(): Collection
    {
        return $this->children;
    }

    public function addChild(self $child): self
    {
        if (!$this->children->contains($child)) {
            $this->children[] = $child;
            $child->setParent($this);
        }

        return $this;
    }

    public function removeChild(self $child): self
    {
        if ($this->children->removeElement($child)) {
            // set the owning side to null (unless already changed)
            if ($child->getParent() === $this) {
                $child->setParent(null);
            }
        }

        return $this;
    }
}

src/Form/ArticleType.php
<?php

namespace App\Form;

use App\Entity\Article;
use App\Entity\Theme;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ArticleType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('publishedAt', null, [
            'label' => 'Published At (nothing is Unpublished)',
            'attr' => [
                'class' => 'date-field'
            ]
        ]);
        $builder->add('title', null, [
            'label' => 'Title',
        ]);
        $builder->add('url', null, [
            'label' => 'Url',
        ]);

        $builder->add('themes', EntityType::class, [
            'label' => 'Themes',
            'class' => Theme::class,
            'multiple' => true,
            'expanded' => true,
        ]);
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Article::class,
        ]);
    }
}

src/Controller/ArticleController.php
<?php
namespace App\Controller;

use App\Entity\Article;
use App\Entity\Comment;
use App\Form\ArticleType;
use App\Handler\CommentHandler;
use App\Handler\ContactHandler;
use App\Handler\SubscriptionHandler;
use App\Manager\ArticleManager;
use Exception;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Security;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/articles")
 */
class ArticleController extends AbstractController
{
    /**
     * @Route("/sync", name="article_sync")
     * @Security("is_granted('ROLE_SUPER_ADMIN')")
     *
     * @param ArticleManager $articleManager The article manager.
     *
     * @return Response
     * @throws Exception
     */
    public function syncAction(ArticleManager $articleManager): Response
    {
        $articleManager->synchronizeAll();

        $this->addFlash('success', 'The articles have been synchronized.');

        return $this->redirectToRoute('homepage');
    }

    /**
     * @Route("/edit/{url}", name="article_edit")
     * @Security("is_granted('ROLE_SUPER_ADMIN')")
     *
     * @param Request $request The request.
     * @param Article $article The article.
     *
     * @return Response
     */
    public function editAction(Request $request, Article $article): Response
    {
        $form = $this->createForm(ArticleType::class, $article);

        $form->handleRequest($request);
        if ($form->isSubmitted()) {
            if ($form->isValid()) {
                $em = $this->getDoctrine()->getManager();

                $em->persist($article);
                $em->flush();

                $this->addFlash('success', 'The article has been edited.');

                return $this->redirectToRoute('homepage');
            }
        }

        return $this->render('app/article/edit.html.twig', [
            'form' => $form->createView(),
            'article' => $article,
        ]);
    }

    /**
     * @Route("/{url}", name="article_show")
     *
     * @param Request             $request             The request.
     * @param Article             $article             The article.
     * @param CommentHandler      $commentHandler      The comment handler.
     * @param SubscriptionHandler $subscriptionHandler The subscription handler.
     * @param ContactHandler      $contactHandler      The contact handler.
     *
     * @return Response
     */
    public function showAction(
        Request $request,
        Article $article,
        CommentHandler $commentHandler,
        SubscriptionHandler $subscriptionHandler,
        ContactHandler $contactHandler): Response
    {
        if (!$article->getPublishedAt() && !$this->isGranted('ROLE_SUPER_ADMIN')) {
            throw $this->createNotFoundException('Not published');
        }

        $articleUrl = $this->generateUrl('article_show', [
            'url' => $article->getUrl(),
        ]);

        if (count($article->getThemes()) > 0) {
            $commentHandler->setUrl($articleUrl);
            if ($commentHandler->processRequest($request)) {
                return $this->redirect($request->getRequestUri());
            }

            if ($subscriptionHandler->processRequest($request)) {
                return $this->redirect($request->getRequestUri());
            }
        }
        if ($article->getUrl() == 'about-me') {
            if ($contactHandler->processRequest($request)) {
                return $this->redirect($request->getRequestUri());
            }
        }

        $commentRepo = $this->getDoctrine()->getRepository(Comment::class);

        $commentStatuses = [Comment::STATUS_NEW, Comment::STATUS_NOTIFIED, Comment::STATUS_VERIFIED];
        if ($this->isGranted('ROLE_SUPER_ADMIN')) {
            if ($request->query->get('deleted', false)) {
                $commentStatuses = [];
            } else {
                $commentStatuses[] = Comment::STATUS_MANUAL;
            }
        }

        $comments = $commentRepo->getForUrl($articleUrl, $commentStatuses);

        return $this->render('app/article/show.html.twig', array_merge([
            'article' => $article,
            'comments' => $comments,
        ], $commentHandler->getViewParameters(),
            $subscriptionHandler->getViewParameters(),
            $contactHandler->getViewParameters()
        ));
    }

    /**
     * Updates the status of a comment.
     *
     * @Route("/update_status/{id}", name="article_update_status", methods={"POST"})
     * @Security("is_granted('ROLE_SUPER_ADMIN')")
     *
     * @param Request $request The request.
     * @param Comment $comment The comment.
     *
     * @return Response
     */
    public function updateStatusAction(Request $request, Comment $comment): Response
    {
        $newStatus = $request->request->get('status', '');
        if (in_array($newStatus, $comment->getPossibleStatuses())) {
            $comment->setStatus($newStatus);

            $em = $this->getDoctrine()->getManager();

            $em->persist($comment);
            $em->flush();

            $this->addFlash('success', 'Le status a bien été mis à jour vers : ' . $newStatus);
        } else {
            $this->addFlash('danger', 'Cannot set status ' . $newStatus . ' to comment ' . $comment->getId());
        }

        return $this->redirect($comment->getUrl() . '?deleted=1#' . $comment->getAnchor());
    }

    /**
     * @Route("/delete/{url}", name="article_delete", methods={"POST"})
     * @Security("is_granted('ROLE_SUPER_ADMIN')")
     *
     * @param Request $request The request.
     * @param Article $article The article.
     *
     * @return Response
     */
    public function deleteAction(Request $request, Article $article): Response
    {
        $em = $this->getDoctrine()->getManager();

        $em->remove($article);
        $em->flush();

        $this->addFlash('success', 'The article has been deleted.');

        return $this->redirectToRoute('homepage');
    }
}

templates/app/article/edit.html.twig
{% extends 'app/base.html.twig' %}

{% block title %}Edit {{ article.title}} - Geoffrey Huck{% endblock %}
{% block canonical %}<link rel="canonical" href="{{ site_url }}{{ path('theme_edit', { url: article.url }) }}" />{% endblock %}

{% block content %}
    <div class="container">
        <form method="post" action="{{ path('article_delete', { url: article.url }) }}" class="float-right">
            <button type="submit" class="btn">
                Delete article
            </button>
        </form>

        <h1>Edit article {{ article.title }}</h1>

        <form method="post" novalidate>
            {{ form_errors(form) }}

            {{ form_row(form.title) }}
            {{ form_row(form.url) }}
            {{ form_row(form.publishedAt) }}

            <br /><br />
            {{ form_row(form.themes) }}

            {{ form_rest(form) }}

            <button class="btn" type="submit">
                Edit this theme
            </button>
        </form>
    </div>
{% endblock %}

templates/app/article/show.html.twig
{% extends 'app/base.html.twig' %}

{% block metas %}
    <meta property="og:title" content="{{ article.title }}" />
    {% if article.coverWidth %}
        <meta property="og:image" content="{{ site_url }}{{ asset('articles/'~ article.directory ~ '/cover_original.JPG') }}" />
    {% endif %}
    <meta property="og:description" content="{{ article.preview | striptags | trim }}" />
    <meta property="og:url" content="{{ site_url }}{{ path('article_show', { url: article.url }) }}" />
{% endblock %}

{% block title %}{{ article.title}} - Geoffrey Huck{% endblock %}
{% block canonical %}<link rel="canonical" href="{{ site_url }}{{ path('article_show', { url: article.url }) }}" />{% endblock %}

{% macro displayComment(comment, nested = false) %}
    <div class="comment{% if is_granted('ROLE_SUPER_ADMIN') %} comment-status-{{ comment.status }}{% endif %}" id="{{ comment.anchor }}" {% if nested %}style="margin-left: 5px;"{% endif %}>
        {% if is_granted('ROLE_SUPER_ADMIN') %}
            <div class="float-right">
                <form method="post" action="{{ path('article_update_status', { id: comment.id }) }}">
                    <select name="status">
                        {% for status in comment.getPossibleStatuses() %}
                            <option {% if status == comment.status %}selected{% endif%} value="{{ status }}">{{ status }}</option>
                        {% endfor %}
                    </select>
                    <button type="submit" class="btn">
                        Update
                    </button>
                </form>
            </div>
        {% endif %}
        <span class="author">{{ comment.author }}</span> on {{ comment.createdAt | date('d/m/Y H:i:s') }} :
        <br /><br />
        {{ comment.content | nl2br }}
        <br /><br />
        <a href="#comment" data-replyTo="{{ comment.author }} on {{ comment.createdAt | date('d/m/Y H:i:s') }}" class="reply-link">Reply</a>

        {% if comment.children | length %}
            <br /><br />
            {% for child in comment.children %}
                {{ _self.displayComment(child, true) }}
            {% endfor %}
        {% endif %}
    </div>
{% endmacro %}

{% block content %}
    <div class="container">
        {% if is_granted('ROLE_SUPER_ADMIN') %}
            <form method="post" action="{{ path('article_sync') }}" class="float-right">
                <button type="submit" class="btn">
                    Synchronize articles
                </button>
            </form>
        {% endif %}

        <article class="{% if not article.publishedAt %}unpublished{% endif %}">
            {% if is_granted('ROLE_SUPER_ADMIN') %}
                <a href="{{ path('article_edit', { url: article.url }) }}" class="btn float-right">
                    Edit article
                </a>
            {% endif %}

            <h1>{{ article.title }}</h1>
            {% if article.themes | length > 0 and article.publishedAt %}
                Published on {{ article.publishedAt | date('d/m/Y') }}
            {% endif %}

            <hr />

            {% if article.coverWidth %}
                <img src="{{ asset('articles/'~ article.directory ~ '/cover.JPG') }}" width="{{ article.coverWidth }}" height="{{ article.coverHeight }}" />
                <br /><br />
            {% endif %}

            {{ article.content | raw }}
        </article>
    </div>

    {% if comments | length %}
        <hr />
        <div class="container">
            {% for comment in comments %}
                {% if comment.parent is null %}
                    {{ _self.displayComment(comment) }}
                {% endif %}
            {% endfor %}
        </div>
    {% endif %}

    {% if formComment %}
        <hr />
        <div class="container" id="comment">
            <div class="centered">
                <h2>Leave a comment</h2>

                <p>Your email will not appear on the website.</p>

                <form method="post" action="#comment" novalidate>
                    {{ form_errors(formComment) }}

                    <div id="reply-to-container" style="display: none;">
                        {{ form_row(formComment.replyTo) }}
                    </div>
                    {{ form_row(formComment.content) }}
                    {{ form_row(formComment.author) }}
                    {{ form_row(formComment.email) }}

                    {{ form_rest(formComment) }}

                    <button class="btn" type="submit">
                        Let's post it !
                    </button>
                </form>
            </div>
        </div>
    {% endif %}

    {% if formSubscription %}
        <hr />
        <div class="container" id="stay-in-touch">
            <div class="centered">
                <h2>Stayin' in touch</h2>

                <div class="stay-in-touch">
                    <p>You found the content interesting and want to stay in touch ?</p>
                    <form method="post" action="#stay-in-touch">
                        {{ form_errors(formSubscription) }}

                        {{ form_row(formSubscription.name) }}
                        {{ form_row(formSubscription.email) }}

                        {{ form_rest(formSubscription) }}

                        <button class="btn" type="submit">
                            I subscribe !
                        </button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}

    {% if formContact %}
        <hr />
        <div class="container" id="contact">
            <div class="centered">
                <h2>Contact me</h2>

                <div class="contact">
                    <p>You can reach me by filling up this form and I'll answer within 48 hours.</p>
                    <form method="post" action="#contact">
                        {{ form_errors(formContact) }}

                        {{ form_row(formContact.name) }}
                        {{ form_row(formContact.company) }}
                        {{ form_row(formContact.email) }}
                        {{ form_row(formContact.message) }}

                        {{ form_rest(formContact) }}

                        <button class="btn" type="submit">
                            Send !
                        </button>
                    </form>
                </div>
            </div>
        </div>
    {% endif %}
{% endblock %}